### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by nswbmw** [koajs/etag#46]
In v2.x(as well as v3)，When response body is huge, JSON.stringify throw `RangeError: Invalid string length`. So, 

```
etag = calculate(JSON.stringify(body), options);
```

add simple try...catch will be ok?

```
try {
  etag = calculate(JSON.stringify(body), options);
} catch (e) {}
```

**Comment by jonathanong** [comment]
do you mind opening an issue here? https://github.com/jshttp/etag
